name: Linux Static Build
on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # On utilise un conteneur ultra-préparé pour le statique
    container: messense/rust-musl-cross:x86_64-musl
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Static Binary
        run: |
          # On force BoringSSL à ignorer l'assembleur (qui fait planter le build)
          # On met toutes les variantes de noms possibles pour être sûr
          export BORING_BSSL_NO_ASM=1
          export BORING_NO_ASM=1
          
          # Compilation
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: ygege-linux-static
          path: target/x86_64-unknown-linux-musl/release/ygege
