name: Linux Static Build
on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust & Target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools cmake build-essential

      - name: Build Static Binary
        # On définit les variables directement ici pour plus de clarté
        run: |
          export CC=musl-gcc
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: ygege-linux-static
          path: target/x86_64-unknown-linux-musl/release/ygege
